version: '3'

volumes:
  prometheus_data: {}

services:
  php_img_1:
      container_name: ${FINAL_PROJECT_NAME}_php_container_1
      build: ./web1
      expose:
         - ${APACHE_EXPOSED_PORT}
      networks:
         public_net:
             ipv4_address: ${PHP_1_IP}

  php_img_2:
      container_name: ${FINAL_PROJECT_NAME}_php_container_2
      build: ./web2
      expose:
         - ${APACHE_EXPOSED_PORT}
      networks:
         public_net:
             ipv4_address: ${PHP_2_IP}

  php_img_3:
      container_name: ${FINAL_PROJECT_NAME}_php_container_3
      build: ./web3
      expose:
         - ${APACHE_EXPOSED_PORT}
      networks:
         public_net:
             ipv4_address: ${PHP_3_IP}

  haproxy_img:
      build: ./haproxy
      ports:
         - 5000:80
      expose:
         - 80
      networks:
         public_net:
             ipv4_address: ${HA_PROXY_IP}
      environment:
         - PHP_1_IP=${PHP_1_IP}
         - PHP_2_IP=${PHP_2_IP}
         - PHP_3_IP=${PHP_3_IP}
         - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      public_net:
        ipv4_address: ${NODE_EXPORTER_IP}

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      public_net:
        ipv4_address: ${PROMETHEUS_IP}

networks:
  public_net:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: ${NETWORK_SUBNET}


