---
- name: Install required system packages
  ansible.builtin.apt:
    name:  "{{ required_packages }}"
    state: latest

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    state: latest

- name: Add Docker s official GPG key
  ansible.builtin.apt_key:
    url: "{{ docker_key  }} "
    state: present

- name: Verify that we have the key with the fingerprint
  ansible.builtin.apt_key:
    id: 0EBFCD88
    state: present

- name: Set up the stable repository
  ansible.builtin.apt_repository:
    repo: "{{ stable_repo  }}"
    state: present
    update_cache: yes

- name: Update apt packages
  ansible.builtin.apt:
    update_cache: yes

- name: Install docker
  ansible.builtin.apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Create group
  ansible.builtin.group:
     name: docker
     state: present
  become: yes

- name: Add user to docker group
  ansible.builtin.user:
     name: adina
     groups: docker
     append: yes
  become: yes

- name: Install docker-compose
  ansible.builtin.get_url:
    url: "{{ docker_compose_url  }}"
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: pull a Docker image
  docker_image:
    name: "{{ docker_image }}"
    tag: latest
    source: pull
